### ISSUE TITLE
Readme: Short explanation how it does it

### ISSUE THREAD

**Issue by andywer** [diegohaz/webpack-blocks-split-vendor#1]
Hey Diego. Nice to see you published a custom block :)

I have one suggestion that came to my mind when reading the README: It says what it does, but not how. Of course the *what* is more important than the *how*, but I think most people will want to know what the block changes under the hood. Not in-detail, but just very short and concise :)

I myself looked into the code to figure it out, but describing it briefly in the README would be nice.

My suggestion what might be worth to state:
* takes `node_modules/**/*.js` files
* adds a configured CommonChunksPlugin
* uses webpack-md5-hash to make webpack use MD5 hashes + why

**Comment by diegohaz** [comment]
Thank you, @andywer. Will do that asap.

I wonder if that's the right way to publish webpack blocks. I'm going to publish a lot of them because currently I'm working on a project that has several blocks and we want to abstract them from our app, such as `server-source-map`, `start-server`, `run-child-config`, `save-assets`, `load-assets` etc.

**Comment by andywer** [comment]
Cool. If you are going to publish a bunch of them you might want to switch to a monorepo layout and use [lerna](https://github.com/lerna/lerna). It's really not hard, just create a `packages/` directory, create a directory per package and use `lerna` to run npm commands in every package.

webpack-blocks does it like that as well. Otherwise you might risk having a lot of repos that might diverge in some way.
